### ISSUE TITLE
createProcess permission denied 

### ISSUE THREAD

**Issue by revollat** [atom-haskell/win-ghci-wrapper#1]
Hi
I have compiled from source and put the executable in C:\Program Files\Haskell Platform\8.0.1\bin

but I got this error at startup :

`ghci-wrapper.exe: C:\Program Files\Haskell Platform\8.0.1\bin": createProcess: permission denied (Permission denied)
`

can you help please ?

Thanks :)

**Comment by lierdakil** [comment]
Um. It seems like you've put `C:\Program Files\Haskell Platform\8.0.1\bin` as a path to either `stack`, `cabal` or `ghci`? Could you post your ide-haskell-repl settings here?
